# To run use
# docker compose up -d
# connect url
# jdbc:mysql://localhost:3306/wormconnect_dev?allowPublicKeyRetrieval=true&useSSL=false
# username:- root password:- root

version: "3.3"

name: "wormconnect-dev-2"

services:
  mysql:
    build: .
    ports:
      - "3306:3306"
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ""
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
